# make sure to stop postgres running directly in your OS
# docker-compose up -d
# docker-compose up -d --build
# docker-compose logs
# docker-compose stop
# docker-compose rm
version: '3.7'
services:
  db:
    # image: postgres
    build:
      context: .
      dockerfile: Dockerfile-pg
    restart: always
    ports:
      - "5432:5432"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"