# make sure to stop postgres running directly in your OS
# docker-compose up -d --build
# docker-compose logs
# docker-compose stop
# docker-compose rm
# fish:
# function dcrb
#     docker-compose stop && docker-compose rm -f && docker-compose up -d --build
#     sleep 3
#     docker-compose logs
# end
version: '3.7'
services:
 
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - './deploy/postgres:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    expose:
      - 5432
    ports:
      - '5432:5432' # only here for adminer
  
        
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: mvt
    ports:
      - "8080:8080"

  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    expose:
      - 3000
    links:
      - db
      - cache
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
      - VIRTUAL_HOST=flittermouse.io,www.flittermouse.io
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  cache:
    image: redis
    container_name: cache
    expose:
      - 6379
    environment:
      - NETWORK_ACCESS=internal
  
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    environment:
      - DEFAULT_HOST=flittermouse.io
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
      