# make sure to stop postgres running directly in your OS
# docker-compose up -d --build
# docker-compose logs
# docker-compose stop
# docker-compose rm
# fish:
# function dcrb
#     docker-compose stop && docker-compose rm -f && docker-compose up -d --build
#     sleep 3
#     docker-compose logs
# end
version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - './docker/postgres:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eventz
    expose:
      - 5432
    
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: mvt
    ports:
      - "8080:8080"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      # - PGHOST=db
      # - PGUSER=postgres
      # - PGPASSWORD=example
      # - PGDATABASE=eventz

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=EST
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
  
      